# Generated by Django 3.1.5 on 2021-01-21 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_snippet_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='stargazers',
            field=models.ManyToManyField(related_name='stargazers_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.snippet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
