# Generated by Django 3.1.5 on 2021-01-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comment_model_and_stargazers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='updated_on',
            new_name='last_updated',
        ),
    ]
