# Generated by Django 3.1.5 on 2021-01-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_snippet_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='name'),
        ),
    ]
