# Generated by Django 3.1.5 on 2021-01-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_snippet_update_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='uid',
            field=models.CharField(blank=True, max_length=150, verbose_name='uid'),
        ),
    ]
