# Generated by Django 3.1.5 on 2021-01-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_snippet_update_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='secret',
            field=models.BooleanField(default=False, verbose_name='secret'),
        ),
    ]
